create table usuario
(
    id    bigint generated by default as identity
        primary key,
    email varchar(255) not null,
    name  varchar(255) not null,
    cpf   varchar(255) not null,
    senha varchar(50)  not null
);

alter table usuario
    owner to postgres;

